package com.ringtaillemur.analyst.query;

public class OlapQuery {
	public static final String MAKE_LEAD_TIME_FOR_CHANGE = "BEGIN TRAN\n"
		+ "\n"
		+ "\n"
		+ "INSERT INTO lead_time_for_change\n"
		+ "(pull_request_id, first_commit_time, first_review_time, pr_close_time, pr_open_time, repository_id)\n"
		+ "SELECT target_pr.pr_id           AS pull_request_id,\n"
		+ "       commits.first_commit_time AS first_commit_time,\n"
		+ "       review.first_review_time  AS first_review_time,\n"
		+ "       target_pr.pr_close_time   AS pr_close_time,\n"
		+ "       pre.event_time            AS pr_open_time,\n"
		+ "       target_pr.repo_id         as repository_id\n"
		+ "FROM (SELECT pr.pull_request_id  AS pr_id,\n"
		+ "             pr_event.event_time AS pr_close_time,\n"
		+ "             pr.repository_id    as repo_id\n"
		+ "      FROM pull_request_event pr_event\n"
		+ "               JOIN pull_request pr\n"
		+ "                    ON pr_event.pull_request_id = pr.pull_request_id\n"
		+ "               LEFT JOIN\n"
		+ "           (SELECT prd.outgoing_pull_request_id      AS pr_id,\n"
		+ "                   count(prd.source_pull_request_id) AS source_count\n"
		+ "            FROM pull_request_direction prd\n"
		+ "            WHERE prd.process_end = 0\n"
		+ "            GROUP BY prd.outgoing_pull_request_id) pr_source\n"
		+ "           ON pr_source.pr_id = pr.pull_request_id\n"
		+ "      WHERE pr_event.event_type = 'CLOSED'\n"
		+ "        AND pr.process_end = 0\n"
		+ "        AND pr_source.source_count IS NULL) target_pr\n"
		+ "         JOIN\n"
		+ "     (SELECT pull_request_id AS pr_id, MIN(pr_comment.event_time) first_review_time\n"
		+ "      FROM pull_request_comment pr_comment\n"
		+ "      GROUP BY pull_request_id) review\n"
		+ "     ON target_pr.pr_id = review.pr_id\n"
		+ "         JOIN\n"
		+ "     (SELECT pr_commit_table.pull_request_id AS pr_id, c.commit_time AS first_commit_time\n"
		+ "      FROM pull_request_commit_table pr_commit_table\n"
		+ "               JOIN commits c\n"
		+ "                    ON pr_commit_table.commit_id = c.commit_id\n"
		+ "      where pr_commit_table.first_commit = 1) commits\n"
		+ "     ON target_pr.pr_id = commits.pr_id\n"
		+ "         JOIN\n"
		+ "     pull_request_event pre\n"
		+ "     ON pre.pull_request_id = target_pr.pr_id and pre.event_type = 'OPENED';\n"
		+ "\n"
		+ "UPDATE pull_request\n"
		+ "set process_end = 1\n"
		+ "where process_end = 0\n"
		+ "\n"
		+ "COMMIT TRAN\n";
}
