spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://rainmaker-azure-sql-server.database.windows.net:1433;database=RainMakerSystemDB
    username: rainmaker
    password: dkffkrRhfldudndnjstnddl!
  security:
    oauth2:
      client:
        registration:
          github:
            redirectUri: "http://127.0.0.1:8080/login/oauth2/code/github"
            clientId: 8189c16057d124b9324e
            clientSecret: e5231059eb31aa50d69a6a2154708a8a3f88954d
            scope:
              - repo
              - repo:status
              - repo_deployment
              - public_repo
              - repo:invite
              - admin:repo_hook
              - write:repo_hook
              - read:repo_hook
              - admin:org
              - admin:public_key
  jpa:
    database: sql-server
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
