spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://rainmaker-azure-sql-server.database.windows.net:1433;database=RainMakerSystemDB
    username: rainmaker
    password: dkffkrRhfldudndnjstnddl!
  security:
    oauth2:
      client:
        registration:
          github:
            redirectUri: "http://127.0.0.1:8080/login/oauth2/code/github"
            clientId: 42286a47489496b3129b
            clientSecret: 1f5ca003e8d738138300071d1bcf1dc6ad6372d2
            scope:
              - repo
              - repo:status
              - repo_deployment
              - public_repo
              - repo:invite
              - admin:repo_hook
              - write:repo_hook
              - read:repo_hook
              - admin:org
              - admin:public_key
  dev:
    frontendUri : "http://127.0.0.1:3000"
    backendUri : "http://127.0.0.1:8080"
  jpa:
    database: sql-server
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  h2:
    console:
      enabled: true
      path: /h2
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
