package com.ringtaillemur.rainmaker.domain.enumtype;

public enum EventType {
	ASSIGNED, AUTO_MERGE_DISABLED, CLOSED, CONVERTED_TO_DRAFT, EDITED, LABELED, LOCKED, OPENED, READY_FOR_REVIEW, REOPENED, REVIEW_REQUEST_REMOVED, REVIEW_REQUESTED, SYNCHRONIZE, UNASSIGNED, UNLABELED, UNLOCKED
}
