package com.ringtaillemur.analyst.domain;

public enum IssueEventType {
	OPEN, EDITED, DELETED, PINNED, UNPINNED, CLOSED, REOPENED, ASSIGNED, UNASSIGNED, LABELED, UNLABELED, LOCKED, UNLOCKED, TRANSFERRED, MILESTONED, DEMILESTONED
}
