package com.ringtaillemur.rainmaker.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import com.ringtaillemur.rainmaker.domain.view.LeadTimeForChangeSourcePullRequestDetail;
import com.ringtaillemur.rainmaker.domain.view.LeadTimeForChangeSourcePullRequestDetailData;

public interface LeadTimeForChangeSourcePullRequestDetailRepository extends
	JpaRepository<LeadTimeForChangeSourcePullRequestDetail, LeadTimeForChangeSourcePullRequestDetailData> {
}
