name: '[DEPLOY] FE(Vue.js) Code'

on:
  push:
    branches:
      - main
    paths:
      - "SRC/FrontEnd_API/**"
  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  #   branches:
  #     - deploy-frontend

jobs:
  build_and_deploy_job:
    defaults: 
      run: 
        working-directory: "./SRC/FrontEnd_API/rainmaker-front-vue"
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Injection URLconfig.json'
        shell: pwsh
        run: |
          pushd './src'
          echo '
          {
            "myURL" : "https://www.rainmaker.cool",
            "defaultURL" : "https://spring-api-server.azurewebsites.net",
            "clientId" : "42286a47489496b3129b",
            "endURL" : "/login/oauth2/code/github"
          }
          ' >> ./URLconfig.json
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_FOREST_095D4A310 }}
          repo_token: ${{ secrets.AZURE_GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/SRC/FrontEnd_API/rainmaker-front-vue" # App source code path
        # api_location: "/SRC/FrontEnd_API/rainmaker-front-vue/src/api" # Api source code path - optional
          output_location: "dist"
          #Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  # close_pull_request_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   name: Close Pull Request Job
  #   steps:
  #     - name: Close Pull Request
  #       id: closepullrequest
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_FOREST_095D4A310 }}
  #         action: "close"
