name: History Collector Deployment

on:
  push:
    branches:
      - MUAM-383/HistoryCollector자동배포
    paths:
      - "SRC/history_collector/**"

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: github-history-collector     # set this to your function app name on Azure
  POM_XML_DIRECTORY: 'SRC/history_collector'
  POM_FUNCTIONAPP_NAME: historycollector-1661914840110
  JAVA_VERSION: '11.x.x'                      # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: 'reset persistence.xml'
        env:
            SUPER_PERSISTENCE: ${{secrets.HISTORY_COLLECTOR_PERSISTENCE_XML}}
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}/src/main'
          mkdir resources
          mkdir ./resources/META-INF
          echo '${{env.SUPER_PERSISTENCE}}' >> ./resources/META-INF/persistence.xml
          chmod 777 ./resources/META-INF/persistence.xml
          ls ./resources/META-INF/persistence.xml
          popd
      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          mvn clean package
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_HISTORY_COLLECTOR }}
