name:  ETL Deployment Pipeline [Practice]

on:
  push:
    branches:
      - MUAM-366/EtlDeploymentPrivateToPublic
    paths:
      - "SRC/ETLs/analyst/**"

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: github-analystics     # set this to your function app name on Azure
  POM_XML_DIRECTORY: 'SRC/ETLs/analyst'
  POM_FUNCTIONAPP_NAME: analyst-1659606593521
  JAVA_VERSION: '1.8.x'                      # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - uses: microsoft/variable-substitution@v1  
        with: 
          files: '${{env.POM_XML_DIRECTORY}}/test-persistence.xml'
        env:
          javax.persistence.jdbc.driver.value : testtest
          
            
      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          ls
          cat persistence.xml
          mvn clean package
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_ETL }}
          # package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/analyst-1659606593521/${{ env.POM_FUNCTIONAPP_NAME }}'
          # package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
