name: '[PR-TEST] ETL Code'

on:
  pull_request:
    branches:
      - main
    paths:
      - "SRC/ETLs/analyst/**"

env:
  AZURE_FUNCTIONAPP_NAME: github-analystics     
  POM_XML_DIRECTORY: 'SRC/ETLs/analyst'
  POM_FUNCTIONAPP_NAME: analyst-1659606593521
  JAVA_VERSION: '11.x.x'               

jobs:
  build:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Restore Project Dependencies Using Mvn'
      shell: pwsh
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package
        popd