name: '[PR-TEST] History Collector Code'

on:
  pull_request:
    branches:
      - main
    paths:
      - "SRC/history_collector/**"
env:
  AZURE_FUNCTIONAPP_NAME: github-history-collector  
  POM_XML_DIRECTORY: 'SRC/history_collector'
  POM_FUNCTIONAPP_NAME: historycollector-1661914840110
  JAVA_VERSION: '11.x.x'                   

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Restore Project Dependencies Using Mvn'
      shell: pwsh
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package
        popd
