name: Deploy Java project to function app

on:
  push:
    branches: 
      - main 
    paths: 
      - "SRC/ETLs/ETL_function_raw_to_usable/**"

env:
  AZURE_FUNCTION_APP_NAME: rainmaker-mariadb-extracts-result      # set this to your function app name on Azure
  POM_XML_DIRECTORY: 'SRC/ETLs/ETL_function_raw_to_usable'                     # set this to the directory which contains pom.xml file
  POM_FUNCTION_APP_NAME: ETL_function_raw_to_usable        # set this to the function app name in your local development environment
  JAVA_VERSION: '1.8.x'                      # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with Gradle
      shell: bash
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        echo pwd
        gradle wrap
        chmod +x gradlew
        ./gradlew build
        popd
    # - name: 'Restore Project Dependencies Using Mvn'
    #   shell: bash
    #   run: |
    #     pushd './${{ env.POM_XML_DIRECTORY }}'
    #     mvn clean package
    #     mvn azure-functions:package
    #     popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
        package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTION_APP_NAME }}'
        publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}