    name: github trigger 
    
    on:
      push:
        branches: [ main ]
        paths:
          - "./SRC/HTTP Hook Listeners/githubWebhookTrigger/**"
        
    env:
      AZURE_FUNCTIONAPP_NAME: swm-project-github-webhook    # set this to your application's name
      AZURE_FUNCTIONAPP_PACKAGE_PATH: './SRC/HTTP Hook Listeners/githubWebhookTrigger'      # set this to the path to your web app project, defaults to the repository root
      NODE_VERSION: '18.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x, 14.x)

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v2

        - name: Setup Node ${{ env.NODE_VERSION }} Environment
          uses: actions/setup-node@v2
          with:
            node-version: ${{ env.NODE_VERSION }}

        - name: 'Resolve Project Dependencies Using Npm'
          shell: bash
          run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            npm install
            npm run build --if-present
            npm run test --if-present
            popd
        - name: 'Run Azure Functions Action'
          uses: Azure/functions-action@v1
          with:
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
            package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
            publish-profile: ${{ secrets.AZURE_GITHUB_WEBHOOK_AUTH }}